version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: loom-postgres
    environment:
      POSTGRES_DB: loom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - loom-network
    command: ["postgres", "-c", "max_connections=200"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-1:
    build: ./backend
    container_name: loom-backend-1
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/loom
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: 5up3r53cr37k3y7h4715l0ng3n0ughf0rh52564lg0r17hm
      JWT_EXPIRATION: 1000000
      JWT_REFRESH_EXPIRATION: 6000000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - loom-network
    ports:
      - "8081:8080"

  backend-2:
    build: ./backend
    container_name: loom-backend-2
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/loom
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: 5up3r53cr37k3y7h4715l0ng3n0ughf0rh52564lg0r17hm
      JWT_EXPIRATION: 1000000
      JWT_REFRESH_EXPIRATION: 6000000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - loom-network

  frontend:
    build: ./frontend
    container_name: loom-frontend
    networks:
      - loom-network
    depends_on:
      - backend-1
      - backend-2

  nginx:
    image: nginx:alpine
    container_name: loom-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend-1
      - backend-2
    networks:
      - loom-network

networks:
  loom-network:
    driver: bridge

volumes:
  postgres_data:
